package com.rgs.oes;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

import com.alexfu.countdownview.CountDownView;
import com.google.android.material.textfield.TextInputEditText;

public class Test extends AppCompatActivity {

    private CountDownView countDown;
    private TextView textView;
    private TextInputEditText question;




    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test);

        countDown = (CountDownView) findViewById(R.id.count_down);
        textView = (TextView) findViewById(R.id.textView);
        question = (TextInputEditText) findViewById(R.id.question);
        CountDownView countDownView = findViewById(R.id.count_down);
        countDownView.setStartDuration(50000);
        countDownView.start();
        question.setText("JHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDFJHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDFJHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDFJHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDFJHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDFJHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDFJHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDFJHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDFJHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDFJHGDFUKYFGUYIFHGUYGDBFUYGBSDFUYGSDFUYGUYFSDGUYFSDGVUYDSGVFUYKSFDGUYSDGFUYGSDFUYGSDUFGSEUDF");
    }
}
